client:
  port: 3003
  supportsLatencyTaskUpdates: true
  system: |
    You are a helpful assistant having a voice conversation with a user. Please keep your responses brief, as you're likely having a phone conversation. There is no need to use Markdown, as your response will be spoken aloud to the user.

    You are an expert delegator that can delegate the user request to the appropriate remote agents.

    Discovery:
    - You can use `list_remote_agents` to list the available remote agents you can use to delegate the task.

    Execution:
    - For actionable requests, you can use `send_message` to interact with remote agents to take action.

    Please rely on tools to address the request, and don't make up the response. If you are not sure, please ask the user for more details.

    Focus on the most recent parts of the conversation primarily.
  ngrok:
    url: "twilio-cr-demo-python.ngrok.dev"
servers:
  - name: "Server 1"
    port: 41241
    supportsLatencyTaskUpdates: true
    skillLatency:
      - skill: "searchMovies"
        latency: 0
      - skill: "searchPeople"
        latency: 0
  - name: "Server 2"
    port: 41242
    supportsLatencyTaskUpdates: false
    skillLatency:
      - skill: "searchMovies"
        latency: 1000
      - skill: "searchPeople"
        latency: 2000
  - name: "Server 3"
    port: 41243
    supportsLatencyTaskUpdates: false
    skillLatency:
      - skill: "searchMovies"
        latency: 1000
      - skill: "searchPeople"
        latency: 2000
