name: Deploy Frontend (on Vercel)

on: 
  push: 
    branches: 
      - main
    paths: 
      - 'nextjs/**'
  pull_request: 
    paths: 
      - 'nextjs/**'

jobs: 
  deploy-frontend:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-actions@v20
        with: 
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./nextjs
          vercel-args: '--prod'
